version: '3.8'

services:
  image-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
